### PR TITLE
Added tests for S3 blob store

### PR DESCRIPTION
**Pull request by claustres**
This ensure the module works well with https://github.com/jb55/s3-blob-store, eg to avoid issues like https://github.com/feathersjs-ecosystem/feathers-blob/issues/37.

You need to have the following environment variables defined to make it work:
* S3_ACCESS_KEY: your S3 access key
* S3_SECRET_ACCESS_KEY: your S3 secret access key
* S3_BUCKET: : your target S3 bucket

### CODE REVIEW

**Comment by daffl** [comment]
Can we make them pass on CI? The error is

> Error: S3BlobStore bucket option required

**Comment by claustres** [comment]
As mentioned in my comment you need to define some env variables, because some should be kept secret I did not set it in code/config directly. Don't know how you used to manage things like that but the best should be to create a S3 account specifically dedicated to Feathers on AWS so that the members of the team have access.

**Comment by daffl** [comment]
A sorry, missed that when I looked at it again. I just invited you to collaborate as an admin which should allow you to add secret environment variables to the [Travis build setting](https://travis-ci.org/feathersjs-ecosystem/feathers-blob/settings).

**Comment by claustres** [comment]
Synced my account and it seems OK. With respect to AWS do I use my account to create a new user in order to get the keys or do you already have a common account for the Feathers team so that you could generate one ?

**Comment by claustres** [comment]
I've created a AWS user + S3 bucket, tests are passing on my laptop but not on travis, can't still figure out why. I believed it was linked to a `/` in the secret key that [needed to be escaped](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) but does not seem to be that...

**Comment by daffl** [comment]
Do you want to send me a private message with the keys? Then I can give it a quick try, too.

**Comment by claustres** [comment]
Done through slack, let me know.

**Pull request merged**
